
#include <string>
#include <iostream>
#include "../include/globals.h"
#include "../include/scripts.h"
#include "../include/resource.h"
#include "../include/assemble.h"

using namespace std;

int compile(int, char**, string& output);

int init(int arg_count, char** arg){
    error_log("Initializing");

    //Actions
    ve_actions.add("import");
    ve_actions.add("native");
    ve_actions.add("register");

    //Keywords
    ve_keywords.add("on");
    ve_keywords.add("when");
    ve_keywords.add("new");
    ve_keywords.add("unique");
    ve_keywords.add("template");

    //Base Templates
    class_handler.add("String");
    class_handler.add("Number");
    class_handler.add("Byte");
    class_handler.add("Boolean");
    class_handler.add("List");

    //None
    variable_handler.add("none","",SCOPETYPE_GLOBAL,I_NULL);

    //Base Template Functions
    function_handler.add("output","none","",class_handler.find("String"),SCOPETYPE_TEMPLATE);
    function_handler.add("output","none","",class_handler.find("Number"),SCOPETYPE_TEMPLATE);
    function_handler.add("output","none","",class_handler.find("Boolean"),SCOPETYPE_TEMPLATE);
    function_handler.add("input","none","",class_handler.find("String"),SCOPETYPE_TEMPLATE);
    function_handler.add("input","none","",class_handler.find("Number"),SCOPETYPE_TEMPLATE);
    function_handler.add("print","none","",class_handler.find("String"),SCOPETYPE_TEMPLATE);
    function_handler.add("print","none","",class_handler.find("Number"),SCOPETYPE_TEMPLATE);
    function_handler.add("print","none","",class_handler.find("Boolean"),SCOPETYPE_TEMPLATE);
    function_handler.add("wait","none","",class_handler.find("String"),SCOPETYPE_TEMPLATE);

    function_handler.add("string","String","",class_handler.find("Number"),SCOPETYPE_TEMPLATE);
    function_handler.add("number","Number","",class_handler.find("String"),SCOPETYPE_TEMPLATE);

    function_handler.add("string","String","",class_handler.find("Boolean"),SCOPETYPE_TEMPLATE);
    function_handler.add("number","Number","",class_handler.find("Boolean"),SCOPETYPE_TEMPLATE);

    function_handler.add("append","none","",class_handler.find("List"),SCOPETYPE_TEMPLATE);
    function_handler.add("prepend","none","",class_handler.find("List"),SCOPETYPE_TEMPLATE);
    function_handler.add("remove","none","",class_handler.find("List"),SCOPETYPE_TEMPLATE);
    function_handler.add("insert","none","",class_handler.find("List"),SCOPETYPE_TEMPLATE);

    function_handler.add("die","none","",I_NULL,SCOPETYPE_GLOBAL);

    //Open Read and Write Files
    file_read.open(file_read_name.c_str());
    file_write.open(file_write_name.c_str());

    if(package){
        file_write_header.open(file_write_header_name.c_str());
        file_write_register.open(file_write_register_name.c_str());
    }

    //Ensure they are open
    if (!file_read or !file_write){
        error_fatal("Couldn't open files");
        pend();
        return EXIT_FAILURE;
    } else if(package and (!file_write_header or !file_write_register)){
        error_fatal("Couldn't open files");
        pend();
        return EXIT_FAILURE;
    }

    //Variable to contain current line of code that we are extracting
    string line;

    error_log("Extracting");

    //Extract
    while(getline(file_read,line)){
        compile_code += line + "\n";
    }

    //Close the Input File
    file_read.close();

    error_log("Compiling");

    //Include Boomslang Assets
    if(package){
        file_write << "/*This C++ code was generated by boomslang, modify at your own risk*/\n\n#include \"../core/boomslangcore.h\"" << endl << "\nextern int* argc;\nextern char*** argv;\n" << endl;
        file_write_header << "/*This C++ code was generated by boomslang, modify at your own risk*/\n" << endl;
    } else {
        file_write << "/*This C++ code was generated by boomslang, modify at your own risk*/\n\n#include \"../core/boomslangcore.h\"" << endl << "\nint* argc;\nchar*** argv;\n" << endl;
    }

    if(compile(arg_count,arg,ve_main_code)==EXIT_FAILURE) return EXIT_FAILURE;

    file_write.close();

    if(package){
        file_write_header.close();
        file_write_register.close();
    }

    #include "../include/preprocess.h"

    error_log("Assembling");

    if(assemble()==EXIT_FAILURE) return EXIT_FAILURE;

    error_log("Cleaning up");

    #include "../include/cleanup.h"

    error_log("Complete");

    return EXIT_SUCCESS;
}
